version: "3"
services:
     db:
        image: postgres
        container_name: "postgresdb"
        environment:
              POSTGRESQL_USER="postgres" 
              POSTGRESQL_PASS="qwerty1234"
        build:
          context: ./db
        expose:
             - "5432"
    backend:        
        build:           
          context: ./backend
          dockerfile: Dockerfile
        ports:
            - "5000:5000"
        depends-on:  
            - db
  client:
     image: ubuntu
        build:
          command: python client/manage.py migrate
          command: python client/manage.py runserver  0.0.0.0:8000                   
          context: ./client           
        ports:
            - "8000:8000"
        depends_on:
            - backend
  
  
        

