name             'dev'
maintainer       'Laschuk Oleksandr'
maintainer_email 'Laschuk.Oleksandr@gmail.com'
license          'All rights reserved'
description      'Installs/Configures dev'
long_description 'Installs/Configures dev'
version          '0.1.0'
